version: '3.1'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=milo_db
      - POSTGRES_USER=milinhoroot36971992
      - POSTGRES_PASSWORD=NestJs-TypeORM$36971992
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=milinhoroot36971992
    ports:
      - "5050:80"

  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=milo_db
      - MYSQL_ROOT_PASSWORD=NestJsTypeORM36971992
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
    depends_on:
      - postgres

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=NestJsTypeORM36971992
      - PMA_HOST=mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql
